//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarAutomobila.Modeli
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkaAutomobila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarkaAutomobila()
        {
            this.ModelAutomobila = new HashSet<ModelAutomobila>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Drzava { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelAutomobila> ModelAutomobila { get; set; }
    }
}
